version: "3.8"

services:
    nextjs:
        build:
            context: .
            dockerfile: Dockerfile
        # ports:
        #     - 3000:3000
        networks:
            - demo-network
        volumes:
            - test_results:/app/cypress/test-results
        command: npm run cy:run:reporter
        stdin_open: true
        tty: true

    # e2e-chrome:
    #     image: "cypress/included:4.1.0"
    #     build: ./e2e
    #     networks:
    #         - demo-network
    #     container_name: cypress-chrome
    #     command: "--browser chrome"
    #     volumes:
    #         - ./cypress/testruns:/app/cypress/testruns
    #         - ./cypress.json:/app/cypress.json

networks:
    demo-network:
        driver: bridge

volumes:
    test_results:
        driver: local